# Generated by Django 3.0.4 on 2020-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexuser',
            name='name',
        ),
        migrations.AddField(
            model_name='flexuser',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flexuser',
            name='status',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='flexuser',
            name='sur_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='first_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='last_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
