# Generated by Django 2.1.5 on 2020-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='entry_order',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_order_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_order_type',
        ),
    ]
