# Generated by Django 2.1.5 on 2020-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject']},
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.webp', upload_to='avatars'),
        ),
    ]
