# Generated by Django 2.1.5 on 2020-04-03 13:44

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default.webp', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Admin', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Group'),
        ),
    ]
