# Generated by Django 3.0.4 on 2020-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200331_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='sur_name',
            field=models.CharField(max_length=100),
        ),
    ]
