# Generated by Django 2.1.5 on 2020-04-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_semester_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head_of_department',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='head_of_department_short',
            new_name='manager_short',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='head_assistant',
            new_name='assistant',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='head_assistant_short',
            new_name='assistant_short',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='head_of_school',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='head_of_school_short',
            new_name='director_short',
        ),
    ]
