# Generated by Django 2.1.5 on 2020-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200403_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_order_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
