# Generated by Django 2.1.5 on 2020-04-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200409_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexuser',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
    ]
