# Generated by Django 2.1.5 on 2020-04-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_flexuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
    ]
