# Generated by Django 2.1.5 on 2020-04-03 22:18

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200403_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='degree',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Молодший бакалавр', max_length=100, no_check_for_status=True),
        ),
    ]
