# Generated by Django 2.1.5 on 2020-04-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200411_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexuser',
            options={'ordering': ['last_name', 'first_name', 'sur_name', 'username']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number', 'semester']},
        ),
    ]
