# Generated by Django 2.1.5 on 2020-04-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200411_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexuser',
            options={'ordering': ['last_name']},
        ),
    ]
