# Generated by Django 2.1.5 on 2020-04-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200411_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
