# Generated by Django 2.1.5 on 2020-04-11 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200411_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['semester']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Semester'),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.webp', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
        ),
        migrations.AlterField(
            model_name='flexuser',
            name='sur_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Discipline'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Specialty'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
    ]
