# Generated by Django 2.1.5 on 2020-04-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200411_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='old_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
