# Generated by Django 2.1.5 on 2020-04-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_student_old_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='old_degree',
            field=models.CharField(blank=True, default='Молодший спеціаліст', max_length=50, null=True),
        ),
    ]
