# Generated by Django 2.1.5 on 2020-04-19 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200412_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexuser',
            name='change_limit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
